package dsw.rumap.app.msggenerator;

public enum Problem {
    NODE_CANNOT_BE_DELETED,
    NODE_IS_NOT_SELECTED,
    NAME_CANNOT_BE_EMPTY,
    NAME_ALREADY_EXISTS,
    NODE_CANNOT_HAVE_CHILDREN,
    SELECTED_NODE_IS_NOT_PROJECT,
    STROKE_HAS_TO_BE_NUMBER,
    ELEMENTS_ARE_NOT_SELECTED,
    ZOOM_IS_AT_MAX,
    ZOOM_IS_AT_MIN,
    SELECT_EXACTLY_ONE_TERM_TO_CENTRALIZE,
}
