package dsw.rumap.app.msggenerator;

public enum Problem {
    NODE_CANNOT_BE_DELETED,
    NODE_IS_NOT_SELECTED,
    NAME_CANNOT_BE_EMPTY,
    NAME_ALREADY_EXISTS,
    NODE_CANNOT_HAVE_CHILDREN,
    SELECTED_NODE_IS_NOT_PROJECT
}
